name: Discord Release Notifications

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Release Msg
        run: |
          
          VERSION=${GITHUB_REF_NAME#v}

          MODRINTH_URL="https://modrinth.com/mod/moreores+/version/$VERSION"
          CURSEFORGE_URL="https://www.curseforge.com/minecraft/mc-mods/moreores-plus-fabric/files"

          MESSAGE="New version released : $VERSION

          Modrinth: $MODRINTH_URL
          CurseForge: $CURSEFORGE_URL"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"$MESSAGE\"}" \
          ${{ secrets.DISCORD_RELEASE_WEBHOOK }}