name: Discord Release Notifications

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Release Msg
        run: |
          VERSION="${GITHUB_REF_NAME#v}"

          MESSAGE=$(cat <<EOF
          New release published in ${{ github.repository }}: $VERSION

          GitHub Release:
          ${{ github.event.release.html_url }}

          Modrinth:
          https://modrinth.com/mod/moreores+/version/${VERSION}

          CurseForge:
          https://www.curseforge.com/minecraft-mc-mods/moreores/files
          EOF
          )

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": $(echo "$MESSAGE" | jq -Rs .)}" \
            "${{ secrets.DISCORD_RELEASE_WEBHOOK }}"