name: Discord Release Notifications

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Release Msg
        run: |
          VERSION="${GITHUB_REF_NAME#v}"

          MESSAGE="New release published: $VERSION\n\nGitHub Release:\n${{ github.event.release.html_url }}\n\nModrinth:\nhttps://modrinth.com/mod/moreores+/versions/$VERSION\n\nCurseForge:\nhttps://www.curseforge.com/minecraft/mc-mods/moreores-plus-fabric/files"

          PAYLOAD=$(jq -n --arg content "$MESSAGE" '{content: $content}')

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "$PAYLOAD" \
            "${{ secrets.DISCORD_RELEASE_WEBHOOK }}"